### PR TITLE
Demo gifs for emacs

### PR DESCRIPTION
**Pull request by masahi**
You can view rendered gifs at https://github.com/masahi/tvm-ffi-navigator/tree/emacs-gif
It's fun :)

@tqchen @comaniac

### CODE REVIEW

**Comment by tqchen** [comment]
@masahi can you send the PR of the gif content to https://github.com/tvmai/web-data images/ffi-navigator ?

It is always a good idea to separate binary blob from the actual code repo

**Comment by tqchen** [comment]
@masahi please update the PR

**Comment by masahi** [comment]
yes I'm figuring out how to display gifs from remote urls

**Comment by tqchen** [comment]
see #14

**Pull request merged**
